Repository YSCEDC/YSCE, pull requests merged in 2023-07, with the labels that each got.

#35 Working prototype of the server list
  .github/workflows/continuous.yml
  src/CMakeLists.txt
  src/common/fsdef.h
  src/gui/CMakeLists.txt
  src/gui/fsguinetdialog.cpp
  src/gui/fsguinetdialog.h
  src/gui/fsmenu_net.cpp
  src/vcpkg.json
Labels: enhancement, netcode, needs testing, UI/UX

#39 scan all airplanes to skip dead plane in F3 view
  src/core/fssimulation.cpp
Labels: bug, misc, UI/UX

#36 Dogfight AI behavior tweaks
  src/autopilot/fsautopilot.cpp
  src/autopilot/fsdogfightautopilot.cpp
  src/autopilot/fsdogfightautopilot.h
  src/core/fssimulation.cpp
  src/core/fssimulation.h
  src/core/fsweapon.cpp
  src/core/fsweapon.h
  src/util/fsutil.cpp
  src/util/fsutil.h
Labels: enhancement, needs testing, ai

#46 Radar warning receiver on HUD + radar drawing changes
  src/config/fsconfig.cpp
  src/config/fsconfig.h
  src/core/fshud2.cpp
  src/core/fshud2.h
  src/core/fsradar.cpp
  src/core/fsradar.h
  src/core/fssimulation.cpp
  src/core/fssubmenu.cpp
Labels: weapons, misc, UI/UX

#45 Incorporate text-based warning messages into 3D HUD
  src/core/fshud2.cpp
  src/core/fshud2.h
  src/core/fssimulation.cpp
Labels: enhancement, graphics, UI/UX

#34 re-enable "Use Ground Texture" OpenGL setting
  src/core/fsfield.cpp
  src/core/fsfield.h
  src/core/fsgroundsky.h
  src/core/fssimulation.cpp
  src/graphics/common/fstexturemanager.cpp
  src/graphics/common/fstexturemanager.h
  src/graphics/d3d9/fsgroundskyd3d.cpp
  src/graphics/gl/fsgroundskygl.cpp
  src/graphics/gl2.0/fsgroundskygl2.0.cpp
  src/graphics/null/fsgroundskynownd.cpp
Labels: bug, upstream, scenery, graphics, os-agnostic, UI/UX

#59 Environment selector server
  runtime/language/en.uitxt
  runtime/language/ja.uitxt
  src/common/fstextresource.h
  src/core/fsnetwork.cpp
  src/core/fsnetwork.h
Labels: netcode
